workspace:
  base: /go
  path: src/github.com/golwei/drone-app

pipeline:
  build:
    image: golang:latest
    volumes:
      - /root/apps:/go/src/github.com/golwei/drone-app
    commands:
      - go get ./...
      - go build
      - ./drone-app
