workspace:
  base: /go
  path: src/github.com/golwei/drone-app
  
pipeline:
  build:
    image: golang:latest
    commands:
      - go get ./...
      - go build
publish:
    image: plugins/docker
    registry: hub.docker.com
    repo: golwei/droneapptest
    username: golwei
    password: 654654

