workspace:
  base: /go
  path: src/github.com/golwei/drone-app
  
pipeline:
  build:
    image: golang:latest
    commands:
      - go get ./...
      - go build
  docker:
    image: plugins/docker
    username: golwei
    password: 654654
    repo: golwei/bar
    tags: latest
    
