workspace:
  base: /go
  path: src/github.com/golwei/drone-app

pipeline:
  build:
    image: golang:latest
    ports:
      - 8080:8080

    commands:
      - go get ./...
      - go build
      - ./drone-app
